// Auto-generated by deployment script
export const CONTRACTS = {
  MockUSDC: "0x594c461bf180258E292bb68e77C643dc96e4E5F0",
  MockUSDT: "0x4B9A2d935b81890599fbbbbD7821A594C67Fafe3",
  EncryptedUSDC: "0x81872E90986C1488D55313760342d9C13050C27e",
  EncryptedUSDT: "0x182F222b92e414c06354f5c2b2e90AEC0425369d",
  ZSwapPool: "0x95134e52cC1436D7F7B111F430EF7eF938a227B7",
  chainId: 11155111,
  explorerUrl: "https://sepolia.etherscan.io",
} as const;
