import hre from "hardhat";
import * as fs from "fs";
import * as path from "path";

const { ethers } = hre;

/**
 * Deploy MockETH, MockBTC, EncryptedETH, and EncryptedBTC
 * Updates config/contracts.ts with new addresses
 */

async function main() {
  console.log("🚀 Starting ETH & BTC Token Deployment on Sepolia...\n");

  const [deployer] = await ethers.getSigners();
  console.log("📝 Deploying contracts with account:", deployer.address);
  console.log("💰 Account balance:", ethers.formatEther(await ethers.provider.getBalance(deployer.address)), "ETH\n");

  // Get ZSwapPool address from existing config
  const ZSwapPool = "0xd6D7358beD60526d4f2DF48F11eD7708c103D749";
  console.log("🔗 Using existing ZSwapPool:", ZSwapPool);

  // STEP 1: Deploy MockETH
  console.log("\n1️⃣  Deploying MockETH...");
  const MockETH = await ethers.getContractFactory("MockETH");
  const mockETH = await MockETH.deploy();
  await mockETH.waitForDeployment();
  const mockETHAddress = await mockETH.getAddress();
  console.log("   ✅ MockETH deployed to:", mockETHAddress);

  // STEP 2: Deploy MockBTC
  console.log("\n2️⃣  Deploying MockBTC...");
  const MockBTC = await ethers.getContractFactory("MockBTC");
  const mockBTC = await MockBTC.deploy();
  await mockBTC.waitForDeployment();
  const mockBTCAddress = await mockBTC.getAddress();
  console.log("   ✅ MockBTC deployed to:", mockBTCAddress);

  // STEP 3: Deploy EncryptedETH
  console.log("\n3️⃣  Deploying EncryptedETH...");
  const EncryptedETH = await ethers.getContractFactory("EncryptedETH");
  const encryptedETH = await EncryptedETH.deploy(mockETHAddress, ZSwapPool);
  await encryptedETH.waitForDeployment();
  const encryptedETHAddress = await encryptedETH.getAddress();
  console.log("   ✅ EncryptedETH deployed to:", encryptedETHAddress);

  // STEP 4: Deploy EncryptedBTC
  console.log("\n4️⃣  Deploying EncryptedBTC...");
  const EncryptedBTC = await ethers.getContractFactory("EncryptedBTC");
  const encryptedBTC = await EncryptedBTC.deploy(mockBTCAddress, ZSwapPool);
  await encryptedBTC.waitForDeployment();
  const encryptedBTCAddress = await encryptedBTC.getAddress();
  console.log("   ✅ EncryptedBTC deployed to:", encryptedBTCAddress);

  // STEP 5: Update config
  console.log("\n💾 Updating config/contracts.ts...");
  updateConfigFile({
    MockETH: mockETHAddress,
    MockBTC: mockBTCAddress,
    EncryptedETH: encryptedETHAddress,
    EncryptedBTC: encryptedBTCAddress,
  });

  // STEP 6: Display summary
  console.log("\n" + "=".repeat(60));
  console.log("🎉 ETH & BTC Token Deployment Complete!");
  console.log("=".repeat(60));
  console.log("\n📋 Deployed Contract Addresses:");
  console.log("   MockETH:        ", mockETHAddress);
  console.log("   MockBTC:        ", mockBTCAddress);
  console.log("   EncryptedETH:   ", encryptedETHAddress);
  console.log("   EncryptedBTC:   ", encryptedBTCAddress);
  console.log("\n🔗 View on Etherscan:");
  console.log("   https://sepolia.etherscan.io/address/" + mockETHAddress);
  console.log("\n✅ Addresses saved to: config/contracts.ts");
  console.log("=".repeat(60) + "\n");
}

/**
 * Update config/contracts.ts with new ETH and BTC addresses
 */
function updateConfigFile(newAddresses: {
  MockETH: string;
  MockBTC: string;
  EncryptedETH: string;
  EncryptedBTC: string;
}) {
  const configPath = path.join(__dirname, "../config/contracts.ts");
  
  const content = `// Auto-generated by deployment script
export const CONTRACTS = {
  MockUSDC: "0x594c461bf180258E292bb68e77C643dc96e4E5F0",
  MockUSDT: "0x4B9A2d935b81890599fbbbbD7821A594C67Fafe3",
  MockETH: "${newAddresses.MockETH}",
  MockBTC: "${newAddresses.MockBTC}",
  EncryptedUSDC: "0xD799BA74a186c139F35c836FAd4C908A22459829",
  EncryptedUSDT: "0xc0B50F52C1bf041EFfAaD2E9672eA9D4bb813660",
  EncryptedETH: "${newAddresses.EncryptedETH}",
  EncryptedBTC: "${newAddresses.EncryptedBTC}",
  ZSwapPool: "0xd6D7358beD60526d4f2DF48F11eD7708c103D749",
  chainId: 11155111,
  explorerUrl: "https://sepolia.etherscan.io",
} as const;

// Simple pool key generator for simplified deployment
export function getPoolKey() {
  return {
    currency0: CONTRACTS.EncryptedUSDC,
    currency1: CONTRACTS.EncryptedUSDT,
    fee: 3000,
    tickSpacing: 60,
    hooks: CONTRACTS.ZSwapPool,
  };
}
`;

  fs.writeFileSync(configPath, content, "utf-8");
  console.log("   ✅ Saved to:", configPath);
}

// Execute deployment
main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("\n❌ Deployment failed:");
    console.error(error);
    process.exit(1);
  });
