const { ethers } = require("ethers");
const fs = require("fs");
const path = require("path");
const solc = require("solc");

/**
 * Simple deployment script using ethers.js directly
 * Compiles and deploys ZSwap contracts to Sepolia
 */

// Load contracts
function compileContract(contractName, sourceFile) {
  console.log(`📝 Compiling ${contractName}...`);
  const source = fs.readFileSync(sourceFile, "utf8");
  
  const input = {
    language: "Solidity",
    sources: {
      [contractName]: {
        content: source
      }
    },
    settings: {
      outputSelection: {
        "*": {
          "*": ["abi", "evm.bytecode"]
        }
      },
      optimizer: {
        enabled: true,
        runs: 200
      }
    }
  };
  
  const output = JSON.parse(solc.compile(JSON.stringify(input)));
  
  if (output.errors) {
    output.errors.forEach(err => {
      if (err.severity === "error") {
        console.error(err.formattedMessage);
        process.exit(1);
      }
    });
  }
  
  const contract = output.contracts[contractName][contractName.split(".")[0]];
  return {
    abi: contract.abi,
    bytecode: contract.evm.bytecode.object
  };
}

async function main() {
  console.log("🚀 Starting ZSwap Deployment on Sepolia...\n");
  
  // Setup provider and wallet
  const provider = new ethers.JsonRpcProvider(process.env.SEPOLIA_RPC_URL);
  const wallet = new ethers.Wallet(process.env.DEPLOYER_PRIVATE_KEY, provider);
  
  console.log("📝 Deploying with account:", wallet.address);
  const balance = await provider.getBalance(wallet.address);
  console.log("💰 Account balance:", ethers.formatEther(balance), "ETH\n");
  
  const deployed = {};
  
  // Compile contracts
  const mockUSDC = compileContract("MockUSDC.sol", "contracts/tokens/MockUSDC.sol");
  const mockUSDT = compileContract("MockUSDT.sol", "contracts/tokens/MockUSDT.sol");
  const encUSDC = compileContract("EncryptedUSDCSimple.sol", "contracts/tokens/EncryptedUSDCSimple.sol");
  const encUSDT = compileContract("EncryptedUSDTSimple.sol", "contracts/tokens/EncryptedUSDTSimple.sol");
  const zswap = compileContract("ZSwapSimple.sol", "contracts/core/ZSwapSimple.sol");
  
  // Deploy MockUSDC
  console.log("\n1️⃣  Deploying MockUSDC...");
  const MockUSDC = new ethers.ContractFactory(mockUSDC.abi, mockUSDC.bytecode, wallet);
  const mockUSDCContract = await MockUSDC.deploy();
  await mockUSDCContract.waitForDeployment();
  deployed.MockUSDC = await mockUSDCContract.getAddress();
  console.log("   ✅ MockUSDC deployed to:", deployed.MockUSDC);
  
  // Deploy MockUSDT
  console.log("2️⃣  Deploying MockUSDT...");
  const MockUSDT = new ethers.ContractFactory(mockUSDT.abi, mockUSDT.bytecode, wallet);
  const mockUSDTContract = await MockUSDT.deploy();
  await mockUSDTContract.waitForDeployment();
  deployed.MockUSDT = await mockUSDTContract.getAddress();
  console.log("   ✅ MockUSDT deployed to:", deployed.MockUSDT);
  
  // Deploy ZSwap (with placeholder addresses)
  console.log("\n3️⃣  Deploying ZSwap...");
  const ZSwap = new ethers.ContractFactory(zswap.abi, zswap.bytecode, wallet);
  const zswapContract = await ZSwap.deploy(ethers.ZeroAddress, ethers.ZeroAddress);
  await zswapContract.waitForDeployment();
  deployed.ZSwap = await zswapContract.getAddress();
  console.log("   ✅ ZSwap deployed to:", deployed.ZSwap);
  
  // Deploy EncryptedUSDC
  console.log("4️⃣  Deploying EncryptedUSDC...");
  const EncUSDC = new ethers.ContractFactory(encUSDC.abi, encUSDC.bytecode, wallet);
  const encUSDCContract = await EncUSDC.deploy(deployed.MockUSDC, deployed.ZSwap);
  await encUSDCContract.waitForDeployment();
  deployed.EncryptedUSDC = await encUSDCContract.getAddress();
  console.log("   ✅ EncryptedUSDC deployed to:", deployed.EncryptedUSDC);
  
  // Deploy EncryptedUSDT
  console.log("5️⃣  Deploying EncryptedUSDT...");
  const EncUSDT = new ethers.ContractFactory(encUSDT.abi, encUSDT.bytecode, wallet);
  const encUSDTContract = await EncUSDT.deploy(deployed.MockUSDT, deployed.ZSwap);
  await encUSDTContract.waitForDeployment();
  deployed.EncryptedUSDT = await encUSDTContract.getAddress();
  console.log("   ✅ EncryptedUSDT deployed to:", deployed.EncryptedUSDT);
  
  // Configure ZSwap
  console.log("\n⚙️  Configuring contracts...");
  console.log("   📝 Authorizing deployer as AVS operator...");
  const tx = await zswapContract.setAVSAuthorization(wallet.address, true);
  await tx.wait();
  console.log("   ✅ AVS operator authorized");
  
  // Save addresses
  const configPath = path.join(__dirname, "../config/contracts.ts");
  const configContent = `// Auto-generated by deployment script
export const CONTRACTS = {
  MockUSDC: "${deployed.MockUSDC}",
  MockUSDT: "${deployed.MockUSDT}",
  EncryptedUSDC: "${deployed.EncryptedUSDC}",
  EncryptedUSDT: "${deployed.EncryptedUSDT}",
  ZSwapPool: "${deployed.ZSwap}",
  chainId: 11155111,
  explorerUrl: "https://sepolia.etherscan.io",
} as const;
`;
  
  fs.writeFileSync(configPath, configContent, "utf-8");
  
  // Print summary
  console.log("\n" + "=".repeat(60));
  console.log("🎉 ZSwap Deployment Complete!");
  console.log("=".repeat(60));
  console.log("\n📋 Deployed Contract Addresses:");
  console.log("   MockUSDC:       ", deployed.MockUSDC);
  console.log("   MockUSDT:       ", deployed.MockUSDT);
  console.log("   EncryptedUSDC:  ", deployed.EncryptedUSDC);
  console.log("   EncryptedUSDT:  ", deployed.EncryptedUSDT);
  console.log("   ZSwap:          ", deployed.ZSwap);
  console.log("\n🔗 View on Etherscan:");
  console.log("   https://sepolia.etherscan.io/address/" + deployed.ZSwap);
  console.log("\n✅ Addresses saved to: config/contracts.ts");
  console.log("=".repeat(60) + "\n");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("\n❌ Deployment failed:");
    console.error(error);
    process.exit(1);
  });
